name       : font-droid-ttf
version    : '1.00'
release    : 4
source     :
    - https://solus-project.com/sources/font-droid-ttf.zip : eb4315ca5ad051e3ea4a56455e6878074e85473f5becf7d2acfb6acacc8a04d3
license    : Apache-2.0
component  : desktop.font
summary    : Droid fonts
description: |
    Droid fonts
install    : |
    fontdir=$installdir/usr/share/fonts/truetype/droid/
    install -dm644 $fontdir
    cp -R $workdir/Droid*/*.ttf $fontdir
    chmod -R 00644 $installdir
