name       : font-droid-ttf
version    : '1.00'
release    : 5
source     :
    - https://solus-project.com/sources/font-droid-ttf.tar.xz : 25b29bfe771bcab5b9cb0572e931599a4d8be0d5cf1cb3ae675086f19f2aebf0
license    : Apache-2.0
component  : desktop.font
summary    : Droid fonts
description: |
    Droid fonts
install    : |
    fontdir=$installdir/usr/share/fonts/truetype/droid/
    install -dm644 $fontdir
    cp -R $workdir/Droid*/*.ttf $fontdir
    chmod -R 00644 $installdir
