name       : font-droid-ttf
version    : '1.00'
release    : 7
source     :
    - https://getsol.us/sources/font-droid-ttf.tar.xz : 2f8fc432fa9aa2702a305a8687822a987ba3c69c2ab12643be7fa00c94d0819a
license    : Apache-2.0
component  : desktop.font
summary    : Droid fonts. Includes Fallback and Japanese support.
description: |
    Droid fonts. Includes Fallback and Japanese support.
install    : |
    fontdir=$installdir/usr/share/fonts/truetype/droid/
    install -dm644 $fontdir
    cp -R $workdir/Droid*/*.ttf $fontdir
    chmod -R 00644 $installdir
